# Generated by Django 4.1.6 on 2023-03-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profilepics/default_profile_pic.jpg', null=True, upload_to='images/profilepics/'),
        ),
    ]
