# Generated by Django 4.1.2 on 2022-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_addlistform'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='amenityinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(blank=True, max_length=4, null=True)),
                ('internet', models.CharField(blank=True, max_length=4, null=True)),
                ('pets', models.CharField(blank=True, max_length=4, null=True)),
                ('aircond', models.CharField(blank=True, max_length=4, null=True)),
                ('heating', models.CharField(blank=True, max_length=4, null=True)),
                ('laundry', models.CharField(blank=True, max_length=20, null=True)),
                ('streamingservices', models.CharField(blank=True, max_length=4, null=True)),
                ('addamenityinfo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rentinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyprice', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('securitydeposit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('numbertenants', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('addrentinfo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='addListForm',
        ),
    ]
