# Generated by Django 4.1.2 on 2022-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_addressinformation_amenityinfo_rentinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=12, blank=True, null=True)),
                ('firstname', models.CharField(max_length=12,blank=True, null=True)),
                ('lastname', models.CharField(max_length=12,blank=True, null=True)),
                ('username', models.CharField(max_length=12,blank=True, null=True)),
                ('password', models.CharField(max_length=12,blank=True, null=True)),
            ],
        ),
    ]