# Generated by Django 4.1.2 on 2023-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
