# Generated by Django 4.1.6 on 2023-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
