# Generated by Django 4.1.6 on 2023-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_profile_city_profile_insta_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
