# Generated by Django 4.1.2 on 2023-02-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hello", "0010_addressinformation_user_amenityinfo_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addlistings",
            name="rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addlistings",
            name="zip",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shome",
            name="bath",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shome",
            name="beds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shome",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shome",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="allinformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("zip", models.IntegerField(blank=True, null=True)),
                ("hometype", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "monthlyprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                (
                    "securitydeposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100, null=True
                    ),
                ),
                ("numbertenants", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                (
                    "bath",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=100, null=True
                    ),
                ),
                (
                    "addrentinfo",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("parking", models.CharField(blank=True, max_length=4, null=True)),
                ("internet", models.CharField(blank=True, max_length=4, null=True)),
                ("pets", models.CharField(blank=True, max_length=4, null=True)),
                ("aircond", models.CharField(blank=True, max_length=4, null=True)),
                ("heating", models.CharField(blank=True, max_length=4, null=True)),
                ("laundry", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "streamingservices",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "addamenityinfo",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
