# Generated by Django 4.1.2 on 2023-02-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0011_alter_addlistings_rooms_alter_addlistings_zip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allinformation",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
