# Generated by Django 4.1.2 on 2023-02-26 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0012_allinformation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenityinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rentinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.AlterField(
            model_name='allinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='addressinformation',
        ),
        migrations.DeleteModel(
            name='amenityinfo',
        ),
        migrations.DeleteModel(
            name='rentinformation',
        ),
    ]
