# Generated by Django 4.1.3 on 2023-02-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0013_remove_amenityinfo_user_remove_rentinformation_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allinformation", old_name="images", new_name="image",
        ),
    ]
