# Generated by Django 4.1.6 on 2023-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='addamenityinfo',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='allinformation',
            name='addrentinfo',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
