# Generated by Django 4.1.6 on 2023-03-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_allinformation_addamenityinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='addamenityinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='allinformation',
            name='addrentinfo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
