# Generated by Django 4.1.6 on 2023-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_remove_allinformation_aircond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
