# Generated by Django 4.1.6 on 2023-03-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_alter_allinformation_addamenityinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
