# Generated by Django 4.1.6 on 2023-04-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='changePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
