# Generated by Django 4.1.6 on 2023-03-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_alter_allinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
