# Generated by Django 4.1.6 on 2023-03-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_alter_allinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'hello/images/image_coming_soon.png'%}", null=True, upload_to='images/'),
        ),
    ]
