# Generated by Django 4.1.6 on 2023-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_alter_allinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinformation',
            name='image',
            field=models.ImageField(blank=True, default='images/image_coming_soon.png', null=True, upload_to='images/'),
        ),
    ]
