# Generated by Django 4.1.6 on 2023-03-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_favorite'),
        ('hello', '0027_alter_allinformation_image'),
    ]

    operations = [
    ]
