# Generated by Django 4.1.2 on 2023-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_merge_0016_favorite_0027_alter_allinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
